### ISSUE TITLE
Disable Prettier on Markdown

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#125]
I don't want the format script in package.json to reformat Prettier.

**Comment by jLouzado** [comment]
Why not format Markdown with Prettier @gaearon ?

Just asking incase you had any issues with it; afaik the changes it makes don't affect the rendered output

**Comment by j-f1** [comment]
It changes the code in the code blocks.

**Comment by gaearon** [comment]
Yeah, I'm pretty intentional about indentation etc, don't want it to be messed with
