### ISSUE TITLE
Spell error

### ISSUE THREAD

**Issue by Angelki** [gaearon/overreacted.io#13]
> We know that when say obj.foo, JavaScript actually looks for foo in obj, obj.__proto__, object.__proto__.__proto__, and so on. 

It might be : obj.__proto__.__proto__?

**Comment by xiaohesong** [comment]
yep, i think it may be a typo. so i had submit [PR](https://github.com/gaearon/overreacted.io/pull/12/commits/9d8366fb6b1f287e719b417b6288856188ba313e)

**Comment by Angelki** [comment]
> yep, i think it may be a typo. so i had submit [PR](https://github.com/gaearon/overreacted.io/pull/12/commits/9d8366fb6b1f287e719b417b6288856188ba313e)

ok
