### ISSUE TITLE
Fix CSS properly

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#134]
This hack is ridiculous.

https://github.com/gaearon/overreacted.io/blob/905b6821ecd9a4836118996908baaffb146e7cee/src/components/Layout.js#L72-L74

Would be nice to somehow change the layout so we don't have to "guess" here.

**Comment by gaearon** [comment]
I don't want to change anything visually — just to get rid of the hack

**Comment by gaearon** [comment]
I just care that

- switcher is aligned with the bottom of the header
- switcher retains position while navigating between home page and blog post

I don't mind weird values as long as I don't have to tune two weird values against each other (like I have to now).

**Comment by gariasf** [comment]
There, that commit should do the trick.
Please let me know if there's anything you'd like to change.
