### ISSUE TITLE
Half of page is white when the content is short in Dark mode

### ISSUE THREAD

**Issue by mojtabast** [gaearon/overreacted.io#137]
This happens on [newsletter confirm page](https://overreacted.io/confirm/) and also [thanks page](https://overreacted.io/thanks/).

<img width="1440" alt="screen shot 1397-11-01 at 01 08 39" src="https://user-images.githubusercontent.com/3523430/51445418-d4050f00-1d19-11e9-82b2-c6f590a682f5.png">

**Comment by gaearon** [comment]
Aah thanks
