### ISSUE TITLE
Links in post body causes refresh of the site

### ISSUE THREAD

**Issue by jaworek** [gaearon/overreacted.io#141]
Link that points to "The Elements of UI Engineering" in "Things I Don’t Know as of 2018" causes site to refresh.

https://github.com/gaearon/overreacted.io/blame/master/src/pages/things-i-dont-know-as-of-2018/index.md#L96

**Comment by j-f1** [comment]
This seems to be because the blog post’s content is injected [using `dangerouslySetInnerHTML`](https://github.com/gaearon/overreacted.io/blob/56f8807f5733d735dbdedc4b549dd883951a9214/src/templates/blog-post.js#L123). I’ll see if I can figure something out here.
