### ISSUE TITLE
You Might Also Like

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#178]
I think maybe instead of prev/next links there should be a way to associate posts with other posts (e.g. "related" list in frontmatter header). Then they would show up below the post. Maybe even always suggest just one (to reduce choice anxiety). Could remember which ones you've read in local storage and pick one out of the related list that you haven't read yet, at least on this device.

**Comment by Deano1167** [comment]
Help

**Comment by juancuiule** [comment]
Hi @gaearon do yo know if someone is working on this? I may have time to give it a try.

**Comment by j-f1** [comment]
Would be cool if someone were to create something like Medium’s recommended posts feature, except for linking together independent blogs instead of forcing people to use Medium.

**Comment by juancuiule** [comment]
I'm working on this and have an implementation for `related` in frontmatter header that should be an array of related posts. I think that this coul work with `tags` too...

**Comment by juancuiule** [comment]
> "Could remember which ones you've read in local storage and pick one out of the related list that you haven't read yet, at least on this device."

I would like to add this part of the feature too...

But I'm not sure on how can we mesure if the user red a post... time? scroll?
After that it will be easy to add those slugs in LocalStorage an ommit them from the related list.
