### ISSUE TITLE
Code inside of <a>tag in dark theme looks weird

### ISSUE THREAD

**Issue by cstrnt** [gaearon/overreacted.io#203]
![image](https://user-images.githubusercontent.com/20679094/51837307-5174e480-2303-11e9-95e5-ca4c4100855f.png)

As you can see in the screenshot the box-shadow looks weird when using `<code>` inside the `<a>` tag.

I personally think that there should not be the box-shadow property on the `<a> `when there is a `<code>` tag inside. But it looks fine on white theme though.

**Comment by gaearon** [comment]
Also notable that it only happens on zoom.

**Comment by Frexeptabel** [comment]
Created a PR ( #206 ) with my approach / solution.

**Comment by gokulkrishh** [comment]
@gaearon Simple fix would be adding `padding-bottom: 1px` to the `a` tag style. 
<img width="1680" alt="screenshot_2019-02-04_at_10_30_47_am" src="https://user-images.githubusercontent.com/2944237/52190996-50463900-2868-11e9-9a4c-2dbe5b565ccf.png">

**Comment by Frexeptabel** [comment]
> @gaearon Simple fix would be by adding `padding-bottom: 1px` to the `a` tag style. No issues in both light & dark theme by adding this.
> 
> <img alt="screenshot_2019-02-04_at_10_30_47_am" width="1680" src="https://user-images.githubusercontent.com/2944237/52190996-50463900-2868-11e9-9a4c-2dbe5b565ccf.png">

I added a 2px padding bottom in #206 😄

**Comment by Frexeptabel** [comment]
@gokulkrishh I personally just like the look of 2px more but that just might be my personal opinion.
I guess we need to wait for @gaearon  's opinion!
