### ISSUE TITLE
Render code responsively using Prettier

### ISSUE THREAD

**Issue by Gaelan** [gaearon/overreacted.io#248]
I tweeted at you yesterday complaining about horizontal scrolling behavior, but it occurs to me that there's a better solution: use Prettier in the client to reformat code to fit on the screen. Turns out, I'm not the first one to have this idea—someone has a component for it at https://www.npmjs.com/package/react-prettier-code-tag.

**Comment by gaearon** [comment]
Interesting. I suppose that would increase the bundle a _lot_ though.

**Comment by Gaelan** [comment]
Ooh, yeah. I just tested and Prettier's browser bundle (standalone.js in the latest NPM version) is ~119 KB minified and gzipped. Your posts currently weigh 200-300 KB (loading the post directly with no cache), so that's a pretty big difference.

**Comment by j-f1** [comment]
You could import it in a web worker and update the code blocks when it downloads.
