### ISSUE TITLE
node_modules\pngquant-bin: Command failed.

### ISSUE THREAD

**Issue by nekopipi** [gaearon/overreacted.io#278]
Hi,Dan! I cloned the you blog on my computer.But when I run `Yarn` it told me:

error C:\Users\xsj\front-end\gatsby\overreacted.io\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\Users\xsj\front-end\gatsby\overreacted.io\node_modules\pngquant-bin
Output:
‼ connect ETIMEDOUT 151.101.40.133:443
  ‼ pngquant pre-build test failed
  i compiling from source

Directory: C:\Users\xsj\front-end\gatsby\overreacted.io\node_modules\pngquan

I don't know what happened, and maybe this is not a valuable issue.But can you tell me how to solve it?I really want to build my personal blog just like yours! Can you help me? Thank you!!

**Comment by shirai91** [comment]
i think your environment is not fully setting up. some module have binary files required to build on client's machine to use. So all you needed is install `python` (ver 2.x), `make` and `gcc` on your machine. you can follow node-gyp's installation guide for setting up. [https://github.com/nodejs/node-gyp](url)

**Comment by nekopipi** [comment]
> 
> 
> i think your environment is not fully setting up. some module have binary files required to build on client's machine to use. So all you needed is install `python` (ver 2.x), `make` and `gcc` on your machine. you can follow node-gyp's installation guide for setting up. [https://github.com/nodejs/node-gyp](url)

Thanks ! I will try.

**Comment by elisamueljah** [comment]
I don’t have any understanding of
IT or Code ; really can’t tell u why I joined

**Comment by rakhee-singh** [comment]
I had the same issue. Rebuilding Xcode solved the problem. Steps to rebuild Xcode:
- xcode-select --print-path (prints the path where Xcode is installed)
- sudo rm -r -f [path] (this deleted the Xcode)
- xcode-select --install (installs Xcode)

**Comment by Rakhee06** [comment]
I had the same issue. Rebuilding Xcode solved the problem. Steps to rebuild Xcode:

xcode-select --print-path (prints the path where Xcode is installed)
sudo rm -r -f [path] (this deleted the Xcode)
xcode-select --install (installs Xcode)
