### ISSUE TITLE
Add a post explaining when React creates SyntheticEvents

### ISSUE THREAD

**Issue by brainlessdeveloper** [gaearon/overreacted.io#29]
Congrats on your new blog, the posts are great so far.

Some time ago I asked [this question on StackOverflow](https://stackoverflow.com/questions/52444941/when-does-react-create-syntheticevents) and didn't get a satisfactory answer. I ended up answering and accepting my own answer, because that's the closest I ever got to one.

I think you might know better?

### Original question follows

Right now, this is the way I understand event handling in React:

  1. The native event capture phase happens
  2. The native event reaches target
  3. The native event bubbles back up
  4. React catches it at the `document` layer
  5. React puts it in its `EventPluginHub`
  6. React simulates another full capture/bubble roundtrip for the `SyntheticEvent`
  7. React runs the handlers you built in your code

If my understanding of React internals is correct, and taking into account [this part](https://www.w3.org/TR/uievents/#event-flow) of the HTML spec:

> Event objects are dispatched to an event target. But before dispatch
> can begin, the event object’s propagation path must first be
> determined.

Does React wait until the event bubbles up to `document` to create its `SyntheticEvent`? And if so, why? In the first step of the event's life, all info about its propagation path is known, so they could do it there.

**Comment by brainlessdeveloper** [comment]
I hope this is the right place for a topic suggestion.

**Comment by coocooooo** [comment]
+1

**Comment by gaearon** [comment]
Thanks for suggestion! I'll consider it
