### ISSUE TITLE
Autodeploy to now

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#3]
Currently I have to run

```
yarn build
cd public
now alias $(now) overreacted.io
```

This is annoying. I want it to be done automatically on commit but I couldn't figure out how to write a correct `now.json`.

**Comment by tanaypratap** [comment]
Thank you for bringing `now` to my notice. I didn't know about this amazing tool out there. I think after the blog is complete you should do a __making of your blog__ blog.

**Comment by yeskunall** [comment]
[This](https://zeit.co/docs/v2/integrations/now-for-github/#usage) and [this](https://zeit.co/docs/v2/integrations/now-for-github/#aliasing-the-default-branch) might help.

**Comment by DSchau** [comment]
[This](https://github.com/zeit/now-examples/blob/master/gatsby/now.json) should be the ticket.

(although the distDir seems like it should be public, not dist 🤷‍♂️)

**Comment by amazing-space-invader** [comment]
I tried to use now/static-build, but they crash on `yarn` with err below. This maybe a zeit's bug?

```
error /tmp/5fcdd82b/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /tmp/5fcdd82b/node_modules/pngquant-bin
Output:
⚠ ENOSPC: no space left on device, write
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
```

now.json
```
{
  "version": 2,
  "name": "overreacted.io",
  "alias": "overreacted.io",
  "github": {
    "autoAlias": true
  },
  "builds": [
    {
      "src": "package.json", 
      "use": "@now/static-build",
      "config": {
        "distDir": "public"
      }
    }
  ]
}
```

package.json script for Now to know what to execute
```
scripts: {
  "now-build": "yarn build"
}
```

Another way - build dist on local machine, commit to repo and then use now/static https://zeit.co/docs/v2/deployments/official-builders/static-now-static/

**Comment by somarlyonks** [comment]
consider [#1544](https://github.com/zeit/now-cli/issues/1544) and https://zeit.co/blog/every-push-now

**Comment by gaearon** [comment]
I almost broke the website again trying to use `now.json` so I'm giving up and just doing this b13a88b
