### ISSUE TITLE
Toggle checkbox display dark background for day mode too and redundancy of unit measure of 0px.

### ISSUE THREAD

**Issue by dikshantpatodia** [gaearon/overreacted.io#308]
In src/utils/global.css:
1. Mismatched property value for 'font-style'.
2. Line 60, font property font-family does not have generic default. Added sans-serif.

Logic issue:
1. Toggle checkbox display dark background for day mode too.

Fixes added in src/components/Toggle.js:
- a ternary condition for react-toggle-track.

Fixed added in src/components/Toggle.css
- added for-day and for-night classes to differentiate and added box-shadow to match the feel.

Unit issue in src/components/Toggle.css:
Issue: Unit of measure 'px' is redundant in Toggle.css
- Fixed by replacing 0px to 0.

Kindly help me in opening a pull request @gaearon , fixes are done in my local.

**Comment by j-f1** [comment]
> Kindly help me in opening a pull request @gaearon , fixes are done in my local.

Check out @kentcdodds’s free course on this topic: http://makeapullrequest.com/
