### ISSUE TITLE
Make Twitter cards work

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#4]
Seems like there's no fancy preview

**Comment by ronaiza-cardoso** [comment]
it's about this? https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards.html

**Comment by gaearon** [comment]
Yea

**Comment by tanaypratap** [comment]
This plugin might help you with it. https://www.gatsbyjs.org/packages/gatsby-remark-social-cards/

**Comment by DSchau** [comment]
@tanaypratap I'd probably recommend using [`gatsby-plugin-twitter`](https://www.npmjs.com/package/gatsby-plugin-twitter) instead. It loads the Twitter JS to embed the widget, and you just use the blockquote embed pattern to embed tweets.

e.g. [in the Gatsby docs](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2018-09-17-gatsby-v2.md#ludicrous-mode-aka-faster-data-hot-reloading) and [live here[(https://www.gatsbyjs.org/blog/2018-09-17-gatsby-v2/)

**Comment by tanaypratap** [comment]
@DSchau I think the requirement is to show blog's card view in Twitter and not Twitter in blog. My suggestion was to solve the former. I might be mistaken though. @gaearon would be able to clarify.

**Comment by equinusocio** [comment]
Just add correct meta to each article..

```html
<meta content="@username" name="twitter:creator">
<meta content="summary_large_image" name="twitter:card">
<meta content="Card Title" name="twitter:title">
<meta content="Card Description" name="twitter:description">
```

**Comment by gaearon** [comment]
I just want this to be automatic.

**Comment by DSchau** [comment]
Whoops - circling back to this.

@tanaypratap you are correct, I was incorrect 😬 Thanks for the clarification!

@gaearon you'll probably want to use an SEO component like [here](https://github.com/DSchau/gatsby-mail/blob/master/src/components/meta.js). I recommend some sane defaults that can then be overridden at the template level. I'll take a look at this in a sec.

**Comment by equinusocio** [comment]
@DSchau It use react-helmet like said in my comment. 👍
