### ISSUE TITLE
mdx || cms

### ISSUE THREAD

**Issue by vitordino** [gaearon/overreacted.io#40]
i wondered if it's worth it, or if make any sense to you, implementing `mdx` or at least some kind of cms (probably netlify-cms), i have some experience in it — even on more complex sites like my [university's news lab](https://campus.fac.unb.br/) and would be glad to tackle this too.

**Comment by dardub** [comment]
I think netlify-cms is a waste of time to set up. Markdown is a very nice tool for writing blog posts. Keep it simple. :)

Just my two cents.

**Comment by vitordino** [comment]
yeah, just read some things, and he really just use the editor.. 

mdx would be cool, but I think if he need any react environment, he would use a codesandbox or anything alike..

closing this
