### ISSUE TITLE
Очень важен перевод 'A Complete Guide to useEffect' на русский 

### ISSUE THREAD

**Issue by retyui** [gaearon/overreacted.io#405]
В тветтере видел твит, что все переводы статей (overreacted.io) на русский будут авторские 
И как результат нехватки времени мы получили только 2 статьи (https://overreacted.io/ru/)
Есть ли желание продолжить авторские переводы?

**Comment by gaearon** [comment]
На это уходит много времени, и сейчас пока кажется важнее писать на английском новые посты чем переводить старые. Но могу постараться продраться если кажется, что важно.

**Comment by deman4ik** [comment]
Кто-то уже [перевел ](https://habr.com/ru/company/ruvds/blog/445276/)
