### ISSUE TITLE
Edit on github link 404

### ISSUE THREAD

**Issue by farskid** [gaearon/overreacted.io#41]
For some reason, the page https://overreacted.io/optimized-for-change/ isn't available on the repository hence the "Edit on Github" link points to 404 on Github.

<img width="930" alt="screen shot 2018-12-12 at 12 44 23" src="https://user-images.githubusercontent.com/8332043/49864672-afa93f00-fe0b-11e8-9f3f-3d5453e55127.png">

**Comment by farskid** [comment]
It works after: https://github.com/gaearon/overreacted.io/commit/4f0688ef60f09a083c20a6c85e18bd948e5cd9c4

**Comment by gaearon** [comment]
yeah forgot to push
