### ISSUE TITLE
Images are broken in the build

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#43]
1. Revert https://github.com/gaearon/overreacted.io/commit/ec340febed133f3e7ec2c1f9a863108dd0f02cda
2. `yarn build`

The `public` folder post is broken — images don't exist at generated path. I don't know why. Works in `dev`.

cc @DSchau

**Comment by gaearon** [comment]
This was *not* fixed by https://github.com/gaearon/overreacted.io/pull/46.

**Comment by gaearon** [comment]
This is really embarrassing. Why does it keep happening?

**Comment by DSchau** [comment]
@gaeron sorry about that! Do you have an example post or posts where this is happening?

Does it only seem to happen on the built site intermittently, or is it something you can reproduce pretty reliably?

**Comment by gaearon** [comment]
It happens on every deploy, in every post with images. (https://github.com/gaearon/overreacted.io/commit/ec340febed133f3e7ec2c1f9a863108dd0f02cda is an example)

**Comment by gaearon** [comment]
Seems like bumping deps again (https://github.com/gaearon/overreacted.io/commit/fece90fde990c4de6b6f7fad6bd5fc110115b155) may have resolved it. I'll close again for now but if it resurfaces we'll know it's intermittent.

**Comment by gaearon** [comment]
It happened agaaaaain

**Comment by gaearon** [comment]
Clearing `node_modules` and cache and rebuilding seems to fix it.

**Comment by sidharthachatterjee** [comment]
So sorry you're seeing this @gaearon 

We cache a bunch of stuff in the `.cache` directory and building (based on your package.json) runs "build": "rm -rf public && gatsby build" which deletes `public` and not `.cache`

**Comment by sidharthachatterjee** [comment]
Sending you a PR in a minute

**Comment by gaearon** [comment]
Right. I thought it's safe to leave the cache but I'll add a thing that clears it.

**Comment by gaearon** [comment]
https://github.com/gaearon/overreacted.io/commit/7e00945b03b4ae8ef3eb60f73141341acf9ae261?

**Comment by sidharthachatterjee** [comment]
Perfect

**Comment by sidharthachatterjee** [comment]
So Netlify's build image at https://github.com/netlify/build-image/blob/65e07189f42d3cc797f1dfe86e197b914a6a5c85/run-build-functions.sh#L41 caches `.cache` 

That's why some builds were failing (mismatch of public and .cache) and some weren't (presumably when you forced a build without cache)

**Comment by gaearon** [comment]
I guess we can close this, hasn't happened since. It's still deeply confusing that `.cache` needs to be cleared before a deploy.
