### ISSUE TITLE
https://www.overreacted.io/ throwing a 404

### ISSUE THREAD

**Issue by akhilome** [gaearon/overreacted.io#440]
See the following image for more context 👇 

![image](https://user-images.githubusercontent.com/15332525/55295930-af5ca000-540a-11e9-866e-820f1de76799.png)

Would a new `alias` within the `now.json` file handle for this? Or an outright redirection?

**Comment by leerob** [comment]
Yep, you'll want to have two aliases. One for `www` and another without. 

```
"alias": ["overreacted.io", "www.overreacted.io"],
```
I'm doing the same thing for [my site deployed with Now](https://github.com/leerob/leerob.io/blob/master/now.json#L2).
