### ISSUE TITLE
Web site blocked for Cuba.

### ISSUE THREAD

**Issue by apenab** [gaearon/overreacted.io#454]
This site is now blocked for Cuba..🤷🤷

**Comment by j-f1** [comment]
Does https://carbon.now.sh work for you? It runs on the same hosting platform.

**Comment by apenab** [comment]
This site is blocked for Cuba....😢

**Comment by ktowen** [comment]
Both sites are blocked for Cuba

**Comment by j-f1** [comment]
cc @rauchg — is there anything you can do to unblock Now in Cuba?

**Comment by LuisPaGarcia** [comment]
The restriction comes from inside.

> Internet censorship in Cuba comes in two forms: directly preventing access to certain websites and systematically limited infrastructure to access the internet cheaply or at all

https://en.wikipedia.org/wiki/Internet_censorship_in_Cuba

**Comment by carburo** [comment]
The restriction does not come from inside. This probably has to do with Now's GCP infrastructure (GCP blocks access from Cuba and other US sanctioned countries). In the meantime a VPN is the way to go.

**Comment by rootlinux2** [comment]
Hi, to all, I can help with this ISSUE without VPN, I recently migrated some projects to NOW and faced the same problem, NOW is hosting on google datacenter and is blocked for all US sanctioned countries.
The solution for me was to use Cloudflare as a proxy server. [Zeit Doc](https://zeit.co/docs/v1/guides/how-to-use-cloudflare/)
Any doubt feel free to contact
