### ISSUE TITLE
Post license is too restrictive?

### ISSUE THREAD

**Issue by jkillian** [gaearon/overreacted.io#473]
The [current posts license](https://github.com/gaearon/overreacted.io/blob/cdb8561e0a71b67d5e9b6543079a5d55b4c92377/LICENSE-posts) reads as follows:

```
Copyright (c) Dan Abramov and the contributors.
All rights reserved.
```

Unfortunately, I believe this means that the code samples in your posts are strictly licensed and cannot be used by others. For example, I wanted to borrow your [`useInterval` implementation](https://overreacted.io/making-setinterval-declarative-with-react-hooks/#extracting-a-hook), but unfortunately this is likely technically illegal. I know in all reality you are likely perfectly fine with others using this code and would never make a copyright claim, but it'd be nicer to have a more permissive license codifying this!

**Comment by gaearon** [comment]
Happy to take a PR adding a separate license for code snippets. I'd like to keep posts restrictive because I don't want people selling them or reposting without attribution.

**Comment by eps1lon** [comment]
This can be closed now that https://github.com/gaearon/overreacted.io/pull/557 is merged.
