### ISSUE TITLE
Set up newsletter?

### ISSUE THREAD

**Issue by gaearon** [gaearon/overreacted.io#5]
Dunno how

**Comment by dsznajder** [comment]
@gaearon Maybe this would be useful: [gatsby-plugin-mailchimp](https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/) :)

**Comment by talves** [comment]
Dan has some homework to do on this one. He will hit 20K subscribers in the first month or so probably. I have nothing bad to say about mailchimp and use it for some of my customers who are non-profit and US only.  That will not be the case here.

With GDPR and the international community as subscribers, you get the fun of making sure it is all covered. Once they sign up for the newsletter, game on! Although [like mailchimp](https://mailchimp.com/help/about-the-general-data-protection-regulation/) most services help you to identify how you are going to handle these items or at least where to start to address you are compliant.

**Comment by gaearon** [comment]
Actually I'm thinking maybe newsletter is a wrong format for this. I want this to be a place people intentionally go look at for something new. Not something that drops into their already oversaturated inboxes. It's probably worse for short term engagement but I think it's better for this blog's format. For people who want to follow there's always going to be RSS.

**Comment by gaearon** [comment]
Okay, here goes

https://github.com/gaearon/overreacted.io/pull/55
