### ISSUE TITLE
Overreacted is down

### ISSUE THREAD

**Issue by ChaituKNag** [gaearon/overreacted.io#530]
I see that overreacted.io hosted on Zeit shows a 500 INTERNAL SERVER error while loading the home page.

![image](https://user-images.githubusercontent.com/13428505/67412833-a6693100-f5dd-11e9-9054-7b838ea2b9ed.png)

**Comment by j-f1** [comment]
It works fine for me.

**Comment by ChaituKNag** [comment]
Works fine for me too now. Thanks. Is there a better way to reach out for such issues in future?
