### ISSUE TITLE
question about React Hooks

### ISSUE THREAD

**Issue by andrepadez** [gaearon/overreacted.io#539]
Hi Dan, sorry for reaching out this way, but i don't use twitter.
I am a somewhat late adopter of React Hooks, I can totally see the advantages they bring, and I started "liking" them, after some forced changes in some class methods I realized they made my life a lot easier.

Anyway, there is one issue i have with them, I have never been able to get a straight answer:
**What about performance?**
I mean, imagine we're working with something that deals with High Frequency Data. Having a component that is rendered 100 times on a page, and each one might be updated and rerendered multiple times per second. How does the system, namely the Garbage Collector, deals if in each render you're declaring new functions and storing them in memory?
I might be missing something here, but it seems like when using classes, these methods are only being declared once, regardless of how many renders you're dealing with.

Another issue i have with the hooks API and the functional components is that i really like to have separation of concerns and have an issue with having data operations inside what i consider should be an almost pure render operation, but that's just my personal grievances with it.

Anyway, I love working with Hooks, and am gradually changing most of my code to it, fortunately i haven't encountered any performance issue, but i'd really like an informed answer on the question i ask you.

Thank you, (for everything)

André

**Comment by Canopix** [comment]
This is not the right place for your question, this is a personal repo of the blog of Dan. 
Please move your question to React repo or use ReactiFlux to make this question to a lot of people that can respond to it. 

Please respect the right place to make this type of question.
