### ISSUE TITLE
README File missing steps to run locally

### ISSUE THREAD

**Issue by NaumanMoazzam** [gaearon/overreacted.io#54]
As README.md suggested, 
![image](https://user-images.githubusercontent.com/30693949/50231645-152f9980-03d1-11e9-9546-6a697f340c28.png)

I cannot run it. Causing errors. Am i missing anything, or do we need to update README.md ?

EDITED:

![image](https://user-images.githubusercontent.com/30693949/50234056-a5241200-03d6-11e9-8813-9d574e7a88c5.png)

![image](https://user-images.githubusercontent.com/30693949/50234074-aead7a00-03d6-11e9-80ce-9819eddd4228.png)

![image](https://user-images.githubusercontent.com/30693949/50234107-c84ec180-03d6-11e9-9c29-a9463aeb7996.png)

![image](https://user-images.githubusercontent.com/30693949/50234138-d270c000-03d6-11e9-892b-eed122afddb6.png)

![image](https://user-images.githubusercontent.com/30693949/50234169-de5c8200-03d6-11e9-8ce5-75919181d639.png)

**Comment by sinchang** [comment]
please paste error messages in the issue description.

**Comment by sinchang** [comment]
make sure that libpng-dev is installed. https://github.com/imagemin/pngquant-bin#updating-pre-compiled-binaries

**Comment by gaearon** [comment]
Seems like Windows specific issue.

**Comment by NaumanMoazzam** [comment]
Yes, I am using Windows 8.1.
Is there any solution to run on windows?

**Comment by gaearon** [comment]
I don't know.

cc @DSchau

**Comment by DSchau** [comment]
@NaumanMoazzam are you using the Unix subsystem stuff in Windows? Not really sure--these issues tend to be challenging to debug, particularly with the Unix subsystem.

I would recommend first checking out [this issue](https://github.com/papandreou/node-pngquant/issues/5) and validating your PATH.

If that doesn't work, perhaps [this comment](https://github.com/papandreou/node-pngquant/issues/14#issuecomment-406181693) is helpful.

**Comment by NaumanMoazzam** [comment]
@DSchau No, I am not using any Unix subsytem stuff in Windows. I am using Windows 8.1  Pro. And those comments aren't helpful in any way.

**Comment by jackwilsdon** [comment]
@NaumanMoazzam, it looks like you're experiencing [this issue](https://github.com/imagemin/imagemin-pngquant/issues/46)

**Comment by xnng** [comment]
@NaumanMoazzam My pngquant doesn't work properly on win10 either

![image](https://user-images.githubusercontent.com/38936252/50549342-1f397e00-0c96-11e9-9720-59d8094c9b07.png)

But it doesn't matter.

I can install dependencies

![image](https://user-images.githubusercontent.com/38936252/50548856-aaaf1100-0c8e-11e9-9a61-14be3c72608d.png)

I can run it.

![image](https://user-images.githubusercontent.com/38936252/50549004-b69bd280-0c90-11e9-9d88-be12bcf3bf9f.png)

![image](https://user-images.githubusercontent.com/38936252/50548984-66bd0b80-0c90-11e9-8150-8e0f0917f1c4.png)

I can also build it

![image](https://user-images.githubusercontent.com/38936252/50549036-1b572d00-0c91-11e9-91f4-97354c53babe.png)

**Comment by NaumanMoazzam** [comment]
@xnng Do you know anything what I am missing?

**Comment by xnng** [comment]
@NaumanMoazzam What are your node and yarn versions?

**Comment by NaumanMoazzam** [comment]
@xnng Yarn Version == 1.12.3 , Node Version == 8.12.0

@j-f1 yarn --force didn't help me.

**Comment by gaearon** [comment]
I'll close since there's nothing I can help with — hopefully someone will figure it out

**Comment by DSchau** [comment]
@NaumanMoazzam we'd be happy to help you out with a one-off pairing session to help debug this issue.

Feel free to [sign up for one on my Calendly](https://calendly.com/dschau)

Sorry you're having these issues!
