### ISSUE TITLE
Came across a blog post and had a few comments...

### ISSUE THREAD

**Issue by WizardOfAus** [gaearon/overreacted.io#61]
Came across https://overreacted.io/things-i-dont-know-as-of-2018/?fbclid=IwAR1kKjMRUwDL8iIHfltfyJSivQLF3kAXgMz73O_hUR0_NzmTtDPDsspeOZw aka https://github.com/gaearon/overreacted.io/edit/master/src/pages/things-i-dont-know-as-of-2018.md

Found it through a social media post someone shared. Was great but I think it would be much more informative to maybe add a bit about context about what you are working on, how long you have been at programming/software/whatever and maybe general things that you do know well. Otherwise it is currently just like a list of a lot of things that one doesn't know which we know is a lot bigger than what one individual does know :)

**Comment by gaearon** [comment]
https://overreacted.io/the-elements-of-ui-engineering/
