### ISSUE TITLE
Website doesn't show up on Google search

### ISSUE THREAD

**Issue by benibienz** [gaearon/overreacted.io#675]
Not sure if you're aware but if I Google "overreacted dan abramov" the site doesn't show up at all. Same for when I Google article names.

**Comment by benibienz** [comment]
The reason is your robots.txt file disallows all web crawlers

**Comment by SniperBuddy101** [comment]
@benibienz I checked the robots.txt file and it looks fine to me.
I think this can be fixed by submitting the website on https://developers.google.com/search/
@gaearon can you please check?

**Comment by eddyw** [comment]
That's because overreacted.io has `x-robots-tag: noindex` in the response headers, so none of the pages will be indexed by search engines regardless of the contents of `robots.txt` file.

**Comment by SniperBuddy101** [comment]
> That's because overreacted.io has `x-robots-tag: noindex` in the response headers, so none of the pages will be indexed by search engines regardless of the contents of `robots.txt` file.

Got it. Thanks!
