### ISSUE TITLE
Add "comment" feature or the posts

### ISSUE THREAD

**Issue by stmoreau** [gaearon/overreacted.io#7]
It would be great if users were able to comment on the posts and start discussions.

**Comment by tanaypratap** [comment]
This could help. https://www.npmjs.com/package/disqus-react 
No backend server needed, only need to register at disqus.

**Comment by gaearon** [comment]
Thanks, but I intentionally want to keep it read-only for now.

**Comment by PinkaminaDianePie** [comment]
sad. very often I love comments on Medium more than original articles - different opinions and arguing in the comments give a better understanding of the topic. and i suppose this repo issues is not the best place for such discussions.

**Comment by stmoreau** [comment]
@PinkaminaDianePie I trust Dan will come back to this feature when he thinks timing is right. For now I don't think anyone can complain. The content he uploads is 🔥 🔥
