### ISSUE TITLE
Potential typo in "Before You memo()"

### ISSUE THREAD

**Issue by bonniss** [gaearon/overreacted.io#784]
Hi Dan,

I think that the highlight part should change to __use `color`__ to match with the context of the above __Solution 1__.

<img width="650" alt="Screen Shot 2022-12-04 at 00 55 39" src="https://user-images.githubusercontent.com/36831801/205455034-a1659935-afa0-4335-a5a1-508734b42008.png">

Thanks.

**Comment by want-to-sleep** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
