### ISSUE TITLE
Link to Twitter profile is the mobile version

### ISSUE THREAD

**Issue by plibither8** [gaearon/overreacted.io#8]
https://github.com/gaearon/overreacted.io/blob/1f0861587bd219403283ef9dd1a95eac2371ddc1/src/components/Bio.js#L30

The link as of now open the mobile site even on desktops. Removing `mobile.` from the URL should fix it.

**Comment by gaearon** [comment]
That's intentional — mobile website is desktop-friendly and will soon be the default one on desktop too. Also uses React.
