### ISSUE TITLE
Is there an RSS feed? 

### ISSUE THREAD

**Issue by simevidas** [gaearon/overreacted.io#823]
I couldn’t find a feed for your blog. Is there one? If not, please consider adding it.

**Comment by QuantGeekDev** [comment]
> I couldn’t find a feed for your blog. Is there one? If not, please consider adding it.
RSS and Atom, check the /app/rss.xml directory

https://feeder.co/discover/039a3632b3/overreacted-io

**Comment by simevidas** [comment]
I found it:

https://overreacted.io/rss.xml
